/**
 * 
 */
package com.v1r3n.bol;

/**
 * @author viren
 *
 */
public enum NodeType {

	FUNCTION,VARIABLE_DECLARATION, STATEMENT_BLOCK, STATEMENT,OBJECT_INSTANCE,VARIABLE_INSTANCE,NUMBER_INSTANCE,EXPRESSION,OPERATOR,EXPRESSION_GROUP,STRING,COMPARISON,TYPENAME,LOGICAL
}
